In [22]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from prettytable import PrettyTable
from sklearn.model_selection import validation_curve
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [6]:
df = pd.read_csv("pd_speech_features.csv")
#Deleting first row
df.columns = df.iloc[0]
df = df.reindex(df.index.drop(0)).reset_index(drop=True)
df = df.drop('id', 1)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """

,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,locAbsJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,1,0.85247,0.71826,0.57227,240,239,0.00806353,8.68E-05,0.00218,1.76E-05,...,1.562,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,1,0.76686,0.69481,0.53966,234,233,0.008258256,7.31E-05,0.00195,1.61E-05,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.178,1
2,1,0.85083,0.67604,0.58982,232,231,0.00833959,6.04E-05,0.00176,1.47E-05,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,0,0.41121,0.79672,0.59257,178,177,0.010857733,0.000182739,0.00419,4.55E-05,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.846,6.265,4.0603,1
4,0,0.3279,0.79782,0.53028,236,235,0.008161574,0.002668863,0.00535,4.37E-05,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

ستون آیدی را حذف می کنیم چون برای هر کس متمایز است و تغییری در روند کار ایجاد نمی کند به نوعی فیچر ریداکشن انجام می دهیم

- ***Preprocessing***

In [7]:
df.isna().sum()

0
gender                       0
PPE                          0
DFA                          0
RPDE                         0
numPulses                    0
                            ..
tqwt_kurtosisValue_dec_33    0
tqwt_kurtosisValue_dec_34    0
tqwt_kurtosisValue_dec_35    0
tqwt_kurtosisValue_dec_36    0
class                        0
Length: 754, dtype: int64

دنبال داده ای می گردیم که مقدار نداشته باشد، همانطور که مشخص است این دیتاست 
فاقد چنین داده ای است

In [8]:
#Deleting duplicated values
df.drop_duplicates()

,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,locAbsJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,1,0.85247,0.71826,0.57227,240,239,0.00806353,8.68E-05,0.00218,1.76E-05,...,1.562,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,1,0.76686,0.69481,0.53966,234,233,0.008258256,7.31E-05,0.00195,1.61E-05,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.178,1
2,1,0.85083,0.67604,0.58982,232,231,0.00833959,6.04E-05,0.00176,1.47E-05,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,0,0.41121,0.79672,0.59257,178,177,0.010857733,0.000182739,0.00419,4.55E-05,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.846,6.265,4.0603,1
4,0,0.3279,0.79782,0.53028,236,235,0.008161574,0.002668863,0.00535,4.37E-05,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,0,0.80903,0.56355,0.28385,417,416,0.004626942,5.22E-05,0.00064,2.97E-06,...,3.0706,3.019,3.1212,2.4921,3.5844,3.54,3.3805,3.2003,6.8671,0
752,0,0.16084,0.56499,0.59194,415,413,0.004549703,0.000219994,0.00143,6.50E-06,...,1.9704,1.7451,1.8277,2.4976,5.2981,4.2616,6.3042,10.9058,28.417,0
753,0,0.88389,0.72335,0.46815,381,380,0.005069271,0.000102654,0.00076,3.87E-06,...,51.5607,44.4641,26.1586,6.3076,2.8601,2.5361,3.5377,3.3545,5.0424,0
754,0,0.83782,0.7489,0.49823,340,339,0.005679019,5.51E-05,0.00092,5.24E-06,...,19.1607,12.8312,8.9434,2.2044,1.9496,1.9664,2.6801,2.8332,3.7131,0
755,0,0.81304,0.76471,0.46374,340,339,0.005675776,3.71E-05,0.00078,4.40E-06,...,62.9927,21.8152,9.2457,4.8555,3.0551,3.0415,4.0116,2.6217,3.1527,0

In [9]:
y = df['class']
X = df.drop('class', 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 102,test_size = 0.3)
X_train.head()
y.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: class, dtype: object

In [10]:
print(y_test.value_counts('1'))
print(y_train.value_counts('1'))

1    0.762115
0    0.237885
Name: class, dtype: float64
1    0.73913
0    0.26087
Name: class, dtype: float64

همانطور که مشخص است اگر همه داده های تست 1 پیش بینی شوند حدود 76 درصد پاسخ درست خواهیم گفت و اگر همه داده های ترین هم 1 پیش بینی شوند 74 درصد. پس باید به یاد داشته باشیم که دقت در کل باید حتما بیش از این دو مقدار باشد

In [ ]:
#Normalization; all values in range 0 and 1

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

In [ ]:
#Decision Tree

tbl = PrettyTable(["Max Depth", "Accuracy", "Cross Validation"])
print('Best max depth value: ')

#This for loop finds the best value for the hyperparamether(max_depth)
for i in range (20, 30):
    dtc = DecisionTreeClassifier(max_depth = i)
    dtc = dtc.fit(X_train, y_train)
    dtc_pred = dtc.predict(X_test)
    dtc_acc = accuracy_score(dtc_pred, y_test)
    dtc_scores = cross_val_score(dtc, X_train, y_train, cv=5)
    tbl.add_row([i, dtc_acc, dtc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
tbl = PrettyTable(["Min Samples Split", "Accuracy", "Cross Validation"])
print('Best min sample split value: ')

#This for loop finds the best value for the hyperparamether(min_samples_split)
for i in range (2, 20):
    dtc = DecisionTreeClassifier(max_depth = 28, min_samples_split = i)
    dtc = dtc.fit(X_train, y_train)
    dtc_pred = dtc.predict(X_test)
    dtc_acc = accuracy_score(dtc_pred, y_test)
    dtc_scores = cross_val_score(dtc, X_train, y_train, cv=5)
    tbl.add_row([i, dtc_acc, dtc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
tbl = PrettyTable(["Min Samples Leaf", "Accuracy", "Cross Validation"])
print('Best min samples leaf value: ')

#This for loop finds the best value for the hyperparamether(min_samples_leaf)
for i in range(1, 10):
    dtc = DecisionTreeClassifier(max_depth = 28, min_samples_split = 3, min_samples_leaf = i)
    dtc = dtc.fit(X_train, y_train)
    dtc_pred = dtc.predict(X_test)
    dtc_acc = accuracy_score(dtc_pred, y_test)
    dtc_scores = cross_val_score(dtc, X_train, y_train, cv=5)
    tbl.add_row([i, dtc_acc, dtc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
#Set all hyperparamethers
dtc = DecisionTreeClassifier(max_depth = 60, min_samples_split = 2, min_samples_leaf = 7)
dtc = dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
dtc_acc_test = accuracy_score(dtc_pred, y_test)
dtc_acc_train = dtc.score(X_train, y_train)
dtc_scores = cross_val_score(dtc, X_train, y_train, cv=5)
res.add_row([dtc_acc_train, dtc_acc_test, dtc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, dtc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= dtc.classes_).plot()

آنچه به نظر می رسد این است که درستی داده های آموزش داده شده حدود 94 درصد است و داده های تست شده حدود 82 درصد. همچنین کراس ولیدیشن نشان می دهد که حدود 80 درصد می توان به نتیجه مدل اطمینان کرد. همانطور که از نمودار مشخص است از کل تعداد داده ها حدود 35 تا به درستی 0 پیش بینی شده اند. همچنین از ردیف دوم برداشت می شود که 153 داده 1 بوده و 1 به درستی پیش بینی شده است، یعنی حدود 89 درصد

In [ ]:
# KNN

tbl = PrettyTable(["Leaf Size", "Accuracy", "Cross Validation"])
print('Best leaf size value: ')

for i in range(10, 50):
    knc = KNeighborsClassifier(leaf_size = i)
    knc = knc.fit(X_train, y_train)
    knc_pred = knc.predict(X_test)
    knc_scores = cross_val_score(knc, X_train, y_train, cv=5)
    knc_acc = accuracy_score(knc_pred, y_test)
    tbl.add_row([i, knc_acc, knc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
tbl = PrettyTable(["n_neighbors", "Accuracy", "Cross Validation"])
print('Best n_neighbors value: ')

for i in range(1, 20):
    knc = KNeighborsClassifier(leaf_size = 50, n_neighbors = i)
    knc = knc.fit(X_train, y_train)
    knc_pred = knc.predict(X_test)
    knc_scores = cross_val_score(knc, X_train, y_train, cv=5)
    knc_acc = accuracy_score(knc_pred, y_test)
    tbl.add_row([i, knc_acc, knc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
knc = KNeighborsClassifier(leaf_size = 50, n_neighbors = 1)
knc = knc.fit(X_train, y_train)
knc_pred = knc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
knc_acc_test = accuracy_score(knc_pred, y_test)
knc_acc_train = knc.score(X_train, y_train)
knc_scores = cross_val_score(knc, X_train, y_train, cv=5)
res.add_row([knc_acc_train, knc_acc_test, knc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, knc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= knc.classes_).plot()

آنچه به نظر می رسد این است که درستی داده های آموزش داده شده 100 درصد است و داده های تست شده حدود 93 درصد. همچنین کراس ولیدیشن نشان می دهد که حدود 91 درصد می توان به نتیجه مدل اطمینان کرد. همانطور که از نمودار مشخص است از کل تعداد داده ها حدود 46 تا به درستی 0 پیش بینی شده اند. همچنین از ردیف دوم برداشت می شود که 165 1 بوده و 1 به درستی پیش بینی شده است

In [ ]:
# SVM

tbl = PrettyTable(["C", "Accuracy", "Cross Validation"])
print('Best C value: ')

for i in range(50, 100):
    svc = SVC(C=i)
    svc = svc.fit(X_train, y_train)
    svc_pred = svc.predict(X_test)
    svc_acc = accuracy_score(svc_pred, y_test)
    svc_scores = cross_val_score(svc, X_train, y_train, cv=5)
    tbl.add_row([i, svc_acc, svc_scores.mean()])
print(tbl)
tbl.clear()
confusion_matrix(y_test, svc_pred)

In [ ]:
tbl = PrettyTable(['gamma', "Accuracy", "Cross Validation"])
print('Best gamma value: ')

for i in range(1 , 30):
    svc = SVC(C = 80, gamma = i)
    svc = svc.fit(X_train, y_train)
    svc_pred = svc.predict(X_test)
    svc_acc = accuracy_score(svc_pred, y_test)
    svc_scores = cross_val_score(svc, X_train, y_train, cv=5)
    tbl.add_row([i, svc_acc, svc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
svc = SVC(C = 80, gamma = 25)
svc = svc.fit(X_train, y_train)
svc_pred = svc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
svc_acc_test = accuracy_score(svc_pred, y_test)
svc_acc_train = svc.score(X_train, y_train)
svc_scores = cross_val_score(svc, X_train, y_train, cv=5)
res.add_row([svc_acc_train, svc_acc_test, svc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, svc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= svc.classes_).plot()

آنچه به نظر می رسد این است که درستی داده های آموزش داده شده 100 درصد است و داده های تست شده حدود 76 درصد. همچنین کراس ولیدیشن نشان می دهد که حدود 74 درصد می توان به نتیجه مدل اطمینان کرد. از ردیف دوم برداشت می شود که 173 1 بوده و 1 به درستی پیش بینی شده است

In [ ]:
# Random Forest

tbl = PrettyTable(["n_jobs", "Accuracy", "Cross Validation"])
print('Best n_jobs value: ')

for i in range(-10, 0):
    rfc = RandomForestClassifier(n_jobs = i)
    rfc = rfc.fit(X_train, y_train)
    rfc_pred = rfc.predict(X_test)
    rfc_acc = accuracy_score(rfc_pred, y_test)
    rfc_scores = cross_val_score(rfc, X_train, y_train, cv=5)
    tbl.add_row([i, rfc_acc, rfc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
tbl = PrettyTable(["n_estimators", "Accuracy", "Cross Validation"])
print('Best n_estimators value: ')
for i in range(1, 40):
    rfc = RandomForestClassifier(n_jobs = -9, n_estimators = i)
    rfc = rfc.fit(X_train, y_train)
    rfc_pred = rfc.predict(X_test)
    rfc_acc = accuracy_score(rfc_pred, y_test)
    rfc_scores = cross_val_score(rfc, X_train, y_train, cv=5)
    tbl.add_row([i, rfc_acc, rfc_scores.mean()])
print(tbl)
tbl.clear()

In [ ]:
rfc = RandomForestClassifier(n_jobs = -9, n_estimators = 20)
rfc = rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
rfc_acc_test = accuracy_score(rfc_pred, y_test)
rfc_acc_train = rfc.score(X_train, y_train)
rfc_scores = cross_val_score(rfc, X_train, y_train, cv=5)
res.add_row([rfc_acc_train, rfc_acc_test, rfc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, rfc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= rfc.classes_).plot()

آنچه به نظر می رسد این است که درستی داده های آموزش داده شده 100 درصد است و داده های تست شده حدود 86 درصد. همچنین کراس ولیدیشن نشان می دهد که حدود 84 درصد می توان به نتیجه مدل اطمینان کرد.

In [43]:
res = PrettyTable(["Model" ,"Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
res.add_row(['Random Forest', rfc_acc_train, rfc_acc_test, rfc_scores.mean()])
res.add_row(['Decesion tree', dtc_acc_train, dtc_acc_test, dtc_scores.mean()])
res.add_row(['KNN', knc_acc_train, knc_acc_test, knc_scores.mean()])
res.add_row(['SVM', svc_acc_train, svc_acc_test, svc_scores.mean()])
print(res)

+---------------+------------------------+-----------------------+--------------------+
|     Model     | Accuracy of train data | Accuracy of test data |  Cross Validation  |
+---------------+------------------------+-----------------------+--------------------+
| Random Forest |   0.998109640831758    |   0.8458149779735683  | 0.8090925426774485 |
| Decesion tree |   0.9224952741020794   |   0.7533039647577092  | 0.7484995507637018 |
|      KNN      |          1.0           |   0.9118942731277533  | 0.9111949685534592 |
|      SVM      |          1.0           |   0.762114537444934   | 0.7391374663072776 |
+---------------+------------------------+-----------------------+--------------------+

به نظر می آید بهترین مدل برای توصیف این دادگان كي ان ان است چراکه داده ها را 
بهتر و دقیق تر پیش بینی می کند.

In [37]:
pca = PCA(n_components=80)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [ ]:
knc = KNeighborsClassifier(leaf_size = 50, n_neighbors = 1)
knc = knc.fit(X_train, y_train)
knc_pred = knc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
knc_acc_test = accuracy_score(knc_pred, y_test)
knc_acc_train = knc.score(X_train, y_train)
knc_scores = cross_val_score(knc, X_train, y_train, cv=5)
res.add_row([knc_acc_train, knc_acc_test, knc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, knc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= knc.classes_).plot()

In [ ]:
rfc = RandomForestClassifier(n_jobs = -9, n_estimators = 20)
rfc = rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
rfc_acc_test = accuracy_score(rfc_pred, y_test)
rfc_acc_train = rfc.score(X_train, y_train)
rfc_scores = cross_val_score(rfc, X_train, y_train, cv=5)
res.add_row([rfc_acc_train, rfc_acc_test, rfc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, rfc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= rfc.classes_).plot()

In [ ]:
svc = SVC(C = 80, gamma = 25)
svc = svc.fit(X_train, y_train)
svc_pred = svc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
svc_acc_test = accuracy_score(svc_pred, y_test)
svc_acc_train = svc.score(X_train, y_train)
svc_scores = cross_val_score(svc, X_train, y_train, cv=5)
res.add_row([svc_acc_train, svc_acc_test, svc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, svc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= svc.classes_).plot()

In [ ]:
#Set all hyperparamethers
dtc = DecisionTreeClassifier(max_depth = 60, min_samples_split = 2, min_samples_leaf = 7)
dtc = dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)

res = PrettyTable(["Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
dtc_acc_test = accuracy_score(dtc_pred, y_test)
dtc_acc_train = dtc.score(X_train, y_train)
dtc_scores = cross_val_score(dtc, X_train, y_train, cv=5)
res.add_row([dtc_acc_train, dtc_acc_test, dtc_scores.mean()])
print(res)
res.clear()

cm = confusion_matrix(y_test, dtc_pred)
print(cm)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels= dtc.classes_).plot()

In [42]:
res = PrettyTable(["Model" ,"Accuracy of train data", "Accuracy of test data" ,"Cross Validation"])
res.add_row(['Random Forest', rfc_acc_train, rfc_acc_test, rfc_scores.mean()])
res.add_row(['Decesion tree', dtc_acc_train, dtc_acc_test, dtc_scores.mean()])
res.add_row(['KNN', knc_acc_train, knc_acc_test, knc_scores.mean()])
res.add_row(['SVM', svc_acc_train, svc_acc_test, svc_scores.mean()])
print(res)

+---------------+------------------------+-----------------------+--------------------+
|     Model     | Accuracy of train data | Accuracy of test data |  Cross Validation  |
+---------------+------------------------+-----------------------+--------------------+
| Random Forest |   0.998109640831758    |   0.8458149779735683  | 0.8090925426774485 |
| Decesion tree |   0.9224952741020794   |   0.7533039647577092  | 0.7484995507637018 |
|      KNN      |          1.0           |   0.9118942731277533  | 0.9111949685534592 |
|      SVM      |          1.0           |   0.762114537444934   | 0.7391374663072776 |
+---------------+------------------------+-----------------------+--------------------+

همانطور كه بنظر مي رسد همچنان بهترين داده براي توصيف دادگان كي ان ان است  ولي از ديگر دادگان مشخص است كه تغييراتي حاصل شده و با از دست دادن برخي از داده ها خود به خود بنظر مي رسد مقداري دقت كاهش ژيدا كرده است ژس احتمالا براي افزايش دقت بهتر است كمتر داده ها را كم كنيم